name: Run all book tests

on: [push, workflow_dispatch]
env:
  MW_CONNECTOR_CONNECTION_PROFILES: loopbackHttps

jobs:
  my-job:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out RVC3-MATLAB repository (for unit tests)
        uses: actions/checkout@v3
        
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: Check hasDisplay
        uses: matlab-actions/run-command@v1
        with:
          command: feature('HasDisplay')
          
      - name: Check isFigureShowEnabled
        uses: matlab-actions/run-command@v1
        with:
          command: feature('NoFigureWindows')
          
      - name: Run tests
        run: |
          matlab -batch runtests("test/book")
          
      #- name: Run MATLAB Tests
        # Only run tests in folder test/book
        #uses: matlab-actions/run-tests@v1
        #with:
          #select-by-folder: test/book
          #code-coverage-cobertura: code-coverage/coverage.xml
